// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5BsVCDdP5Frq0cxJwcIZCczUkC-8SzHM',
    appId: '1:119717207902:android:5b467fd29cf80a1fd379cf',
    messagingSenderId: '119717207902',
    projectId: 'protagonists-16ae0',
    storageBucket: 'protagonists-16ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCknS4x5SF1gs7WWPcX74I740oA_1rSHZQ',
    appId: '1:119717207902:ios:266958e2da907251d379cf',
    messagingSenderId: '119717207902',
    projectId: 'protagonists-16ae0',
    storageBucket: 'protagonists-16ae0.appspot.com',
    iosClientId: '119717207902-k0a0jrsm35m2iu64tct6evldlbongn92.apps.googleusercontent.com',
    iosBundleId: 'com.example.protagonists',
  );
}
