// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABv3Z9Od3Xj7k661TpOgB58kYtyOzF7PI',
    appId: '1:460166664705:android:3897f9a30ac716b3a5e600',
    messagingSenderId: '460166664705',
    projectId: 'flash-chat-6429b',
    storageBucket: 'flash-chat-6429b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE3DejbbAyQLR2Fy8Pvms7ZR80GbXuW8g',
    appId: '1:460166664705:ios:e4860ec32e12603fa5e600',
    messagingSenderId: '460166664705',
    projectId: 'flash-chat-6429b',
    storageBucket: 'flash-chat-6429b.appspot.com',
    iosClientId: '460166664705-678bt9ajkp70fqog5sq1p6v3i9v7q2qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreDemo',
  );
}
