// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXKG5HhBjJqp5cygIDGdCaq1To_gQfTKA',
    appId: '1:916421099888:android:9dcb63fcb2391adfd64fb5',
    messagingSenderId: '916421099888',
    projectId: 'the-app-354102',
    storageBucket: 'the-app-354102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6coq7x2fVdU8sbrYoKlupkk84z_4_-8E',
    appId: '1:916421099888:ios:b9829317877af652d64fb5',
    messagingSenderId: '916421099888',
    projectId: 'the-app-354102',
    storageBucket: 'the-app-354102.appspot.com',
    androidClientId: '916421099888-gnnl4dcbomq9totrpu46o43iqhcqtbk2.apps.googleusercontent.com',
    iosClientId: '916421099888-fjd5kn523hjcuuasrh70dd1no1goprio.apps.googleusercontent.com',
    iosBundleId: 'com.example.carFirebase',
  );
}
