// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNNvCsDYMHOv-FcsftGz9H7gsJB9pCBE',
    appId: '1:580023066034:android:2e5368a0e4618a295618ab',
    messagingSenderId: '580023066034',
    projectId: 'fir-demo-ee512',
    storageBucket: 'fir-demo-ee512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDftn9IDB4kSI3wcDdvNoD4p1CWvmqlTDk',
    appId: '1:580023066034:ios:00e52ac36ffd1aaa5618ab',
    messagingSenderId: '580023066034',
    projectId: 'fir-demo-ee512',
    storageBucket: 'fir-demo-ee512.appspot.com',
    iosClientId: '580023066034-3203kqu193bomrg3urd6rkcl3dtv9akl.apps.googleusercontent.com',
    iosBundleId: 'com.example.petFirebase',
  );
}
